# Generated by Django 4.0.5 on 2022-06-25 16:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=120)),
                ('first_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedProducts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('amount', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='PayCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_check', models.DateTimeField(auto_now_add=True)),
                ('pay_check_sum', models.DecimalField(decimal_places=2, max_digits=20)),
                ('buyer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shopping_information.buyer')),
                ('purchased_products', models.ManyToManyField(related_name='products', to='shopping_information.purchasedproducts')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shopping_information.shop')),
            ],
        ),
    ]
